import sys
import os
from datetime import datetime
import random

# Add current dir to path to find rare_candy modules
sys.path.append(os.getcwd())

from core.types import Candle, Bias, SignalType, Signal
from core.strategy.trend_pullback import TrendPullbackStrategy
from core.risk.manager import RiskManager
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)

def run_test():
    print("💎 Running Rare Candy Deterministic Replay Test...")
    
    # 1. Generate Synthetic Data (Uptrend)
    candles_1h = []
    price = 1000.0
    for i in range(200):
        price = price * (1.001 if i % 2 == 0 else 0.9995) + (i * 0.1) # Upward drift
        candles_1h.append(Candle(
            timestamp=datetime.now(),
            open=price,
            high=price*1.01,
            low=price*0.99,
            close=price*1.005,
            volume=1000
        ))
        
    candles_15m = [] # Pullback scenario
    price = candles_1h[-1].close
    for i in range(100):
        # Create a dip then recovery
        if 50 < i < 60:
            price *= 0.99 # Dip
        elif i == 60:
            # Reversal candle
            price_open = price
            price = price * 1.01
            candles_15m.append(Candle(
                timestamp=datetime.now(),
                open=price_open, 
                high=price, 
                low=price_open * 0.99, 
                close=price, 
                volume=500
            ))
            continue
        else:
            price *= 1.0001
            
        candles_15m.append(Candle(
            timestamp=datetime.now(),
            open=price,
            high=price*1.001,
            low=price*0.999,
            close=price,
            volume=500
        ))
        
    print(f"Generated {len(candles_1h)} 1h candles, {len(candles_15m)} 15m candles.")
    
    # 2. Initialize Strategy & Risk
    strategy = TrendPullbackStrategy()
    risk = RiskManager(equity=10000.0)
    
    # 3. Evaluate Strategy
    print("Evaluating Strategy...")
    # Feed slice where reversal happened (index 60 in loop, so around 60th candle)
    # Actually just pass all
    signal = strategy.evaluate("BTC/USD", candles_1h, candles_15m)
    
    if signal:
        print(f"✅ Signal Generated: {signal}")
        print(f"   Reason: {signal.reason}")
        
        # 4. Evaluate Risk
        print("Evaluating Risk...")
        decision = risk.evaluate(signal, open_positions={})
        
        if decision.approved:
            print(f"✅ Risk Approved: {decision.quantity} units (${decision.notional:.2f})")
        else:
            print(f"❌ Risk Blocked: {decision.reason}")
    else:
        print("❌ No Signal Generated by Strategy (Synthetic data may need tuning)")
        print("   -> Testing Risk Module with Manual Signal to verify pipeline...")
        
        manual_signal = Signal(
            type=SignalType.ENTRY_LONG,
            symbol="BTC/USD",
            price=1000.0,
            stop_loss=980.0,
            take_profit=1040.0,
            reason="Manual Test Signal",
            strategy_id="manual_test",
            confidence=0.9
        )
        decision = risk.evaluate(manual_signal, open_positions={})
        if decision.approved:
            print(f"✅ Risk System Verified: Approved manual signal. {decision.quantity} units.")
        else:
            print(f"❌ Risk System Verified: Blocked manual signal. Reason: {decision.reason}")
        
    print("\nVerification Complete.")

if __name__ == "__main__":
    run_test()
